### ISSUE TITLE
Failed deployment after authentication setup

### ISSUE THREAD

**Issue by SChioatto** [SAP-samples/sap-btp-side-by-side-extension-learning-journey#10]
Hi,

The deployment after configuration of the approuter is failing due to the approuter app itself and I cannot understand where the issue lies based on the log.
Now I tried deleting the source of the approuter and re-executing the steps several times and also tried to branch to solution/9_add_UI_and_approuter_to_MTA but the issue is not solved either way.

Attaching logs if that's gonna be help identify the issue.

Thansk,

BR

**Comment by Wilyereny** [comment]
I have just the same problem. Please share if you found a solution. Thanks

**Comment by Wilyereny** [comment]
The learning path just got updated and the approuter was changed from Satndalone to manged, they provide a Troubleshooting guide for a problem but with the Standalon version of the approuter. Have anyone gotten some improvement?

**Comment by Wilyereny** [comment]
BTW, using the previous guide i solve the problem by adding more memory through both the manifest and the cockpit to the approuter instance and to the risk-management one. Make sure the tenant mode is marked as dedicated, no share

**Comment by markushaug** [comment]
Hi, as mentioned by @Wilyereny, we have updated the learning journey. From now on, please only post issues in the dedicated learning community group. 

@SChioatto could you please create a post there and also share your log file? 

Please also note, that with the new course update, the latest CAP-version is used. So odds are, that your issues are gone, if you follow the new instructions.
