### ISSUE TITLE
Error: The redirect_uri has an invalid domain

### ISSUE THREAD

**Issue by Wilyereny** [SAP-samples/sap-btp-side-by-side-extension-learning-journey#12]
Hi,
The learning path just got updated and the approuter was changed from Standalone to managed, you provide a Troubleshooting guide for a problem but with the Standalone version of the approuter. Im gettin a "The redirect_uri has an invalid domain." error.

I tried adding a redirect uri but I{m not sure if I'm adding the url right.
![image](https://user-images.githubusercontent.com/79857955/201195636-9d945324-da79-4da9-baad-a12ff31063a1.png)
![noname](https://user-images.githubusercontent.com/79857955/201196077-7c7e02a2-e491-4dfc-b939-83820d16f236.png)

**Comment by markushaug** [comment]
Moved to community group: https://groups.community.sap.com/t5/sap-btp-learning-q-a/the-redirect-uri-has-an-invalid-domain/qaq-p/125252
