### ISSUE TITLE
404 Error 

### ISSUE THREAD

**Issue by itsmesabari** [SAP-samples/sap-btp-side-by-side-extension-learning-journey#13]
![image](https://user-images.githubusercontent.com/42165579/201482579-6018bd50-abb4-4cc3-9393-5b4e9fd31309.png)

**Comment by markushaug** [comment]
Hi, due to a renaming, it's now available at: https://learning.sap.com/learning-journey/building-side-by-side-extensions-on-sap-btp

We have moved some content over to the "Discover SAP BTP Learning Journey".

BR,
Markus

**Comment by itsmesabari** [comment]
Thanks Markus for the update.
